steps:
  - id: Update Permissions
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "chmod"
    args: ["-v","-R", "a+rw","."]
  - id: Build Jekyll Site
    name: "jekyll/jekyll"
    args: ["jekyll","build"]
    env:
      - "JEKYLL_ENV=production"
  - id: Deploy to App Engine
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["app", "deploy"]
timeout: "15m"
